project:
  type: book
  output-dir: docs

book:
  title: "Madagascar rural observatory system data validation, preparation, and georeferencing"
  author: "Florent Bédécarrats"
  date: "01/18/2024"
  repo-url: https://github.com/fBedecarrats/Rural_Obs_Madagascar
  # cover-image: figs/IRD_010664_ORI_small.png
  # cover-image-alt: Déforestation à Madagascar © IRD - Bernard Moizo
  chapters:
    - index.qmd
    - 01-ros-data-catalogue.qmd
    - 02-ros-data-attrition.qmd
    - 03-ros-data-georeferencing.qmd
    - 04-ros-data-preparation.qmd
    - 05-bibliography.qmd
    
bibliography: bibliography.bib

format:
  html:
    theme: cosmo
    code-fold: true

execute:
  warning: false
  error: false
